# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: 'WebNotebook/WebNotebook.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: Docker@2
  displayName: 'Build Image'
  inputs:
    containerRegistry: 'docker aliyun'
    command: 'build'
    Dockerfile: 'WebNotebook/Dockerfile'
    arguments: '-f WebNotebook/Dockerfile'

- task: Docker@2
  displayName: 'Login aliyun'
  inputs:
    containerRegistry: 'docker aliyun'
    command: 'login'

- task: Docker@2
  displayName: 'Push to aliyun'
  inputs:
    containerRegistry: 'docker aliyun'
    repository: 'zohnz/webnotebook'
    command: 'push'
    tags: '$(Build.BuildId)'

- task: SSH@0
  displayName: 'Run aliyun_ssh'
  inputs:
    sshEndpoint: 'aliyun_ssh'
    commands: 'cd /data/deploy/ && docker pull registry.cn-hangzhou.aliyuncs.com/zohnz/webnotebook:$(Build.BuildId) && docker run --name=$(Build.BuildId)  -p 5000:80 -d '
